version: "3.3"
services:
  search-service:
    image: opensearchproject/opensearch:2.11.1
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx1G"
      discovery.type: "single-node"
      plugins.security.disabled: "true"
  cloaked-search:
    image: "gcr.io/ironcore-images/cloaked-search:2.4.3"
    ports:
      - 8675:8675
    volumes:
      - type: bind
        source: ../try-cloaked-search-conf.json
        target: /app/deploy.json
      - type: bind
        source: ../indices
        target: /app/indices
      - type: bind
        source: ../example.key
        target: /secrets/cloaked-search/key1
