version: "3.3"
services:
  search-service:
    image: opensearchproject/opensearch:1.1.0
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx1G"
      discovery.type: "single-node"
  cloaked-search:
    image: "gcr.io/ironcore-images/cloaked-search:0.6.0"
    ports:
      - 8675:8675
    volumes:
      - type: bind
        source: ./try-cloaked-search-open-search-conf.yml
        target: /app/deploy.yml
      - type: bind
        source: ../test-key
        target: /secrets/cloaked-search/key1
