es_url: "http://elasticsearch:9200"
standalone_keys:
  - id: primary-key
    keypath: /secrets/cloaked-search/key1
    primary: true
indices:
  - name: try_cloaked_search
    fields:
      - name: title
        analyzer:
          tokenizer: default
          filters:
            - lowercase
            - terms
            - phrases
            - substring
