apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloaked-search
spec:
  selector:
    matchLabels:
      app: cloaked-search
  template:
    metadata:
      labels:
        app: cloaked-search
    spec:
      containers:
      - name: cloaked-search
        image: cloaked-search-placeholder
        env:
          - name: RUST_LOG
            value: info
        resources:
          limits:
            memory: 500Mi
            cpu: 2
        ports:
          - containerPort: 8675
            name: http
        livenessProbe:
          httpGet:
            path: /_cloaked_search/live
            port: http
        readinessProbe:
          httpGet:
            path: /_cloaked_search/health
            port: http
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
          - name: config
            mountPath: /app/deploy.json
            subPath: deploy.json
          - name: index-config
            mountPath: /app/indices/try_cloaked_search.json
          - name: keys
            mountPath: /secrets/cloaked-search
      securityContext:
        fsGroup: 1001
      volumes:
        - name: config
          configMap:
            name: cloaked-search-config
        - name: index-config
          configMap:
            name: cloaked-search-index-config
        - name: keys
          secret:
            secretName: cloaked-search
