apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloaked-search

resources:
- cs-deploy.yaml
- cs-svc.yaml
- es-deploy.yaml
- es-svc.yaml
- ns.yaml
- pvc.yaml

images:
- name: cloaked-search-placeholder
  newName: gcr.io/ironcore-images/cloaked-search
  newTag: 0.1.48
- name: elasticsearch-placeholder
  newName: elasticsearch
  newTag: 7.14.0
