apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloaked-search

resources:
- cs-deploy.yaml
- cs-svc.yaml
- es-deploy.yaml
- es-svc.yaml
- ns.yaml
- pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - files:
    - config/deploy.yml
    name: cloaked-search

secretGenerator:
  - literals:
    - key1=60e0787286bf350ec4db6a89c54efea38d09238ac80fc9a1401c0291f96bd1ee
    name: cloaked-search

images:
- name: cloaked-search-placeholder
  newName: gcr.io/ironcore-images/cloaked-search
  newTag: "0.6"
- name: elasticsearch-placeholder
  newName: elasticsearch
  newTag: "7.14.0"
